refactor: UserService
Sejong-Java-Study/Gimme-Gonghak-Auth pull request #90
Opened 2024-12-01 19:00 UTC by gmltn9233

## 🔧연결된 이슈
- closed

## 🛠️작업 내용
- UserService 메서드 분리
- 테스트 코드 작성

## 🤷‍♂️PR이 필요한 이유
- 가독성 향상 및 회원 탈퇴, 회원가입 검증, 비밀번호 변경 검증 테스트 코드를 작성하였습니다.

## ✔️PR 체크리스트
- [x] 필요한 테스트를 작성했는가?
- [x] 다른 코드를 깨뜨리지 않았는가?
- [ ] 연결된 이슈 외에 다른 이슈를 해결한 코드가 담겨있는가?

2024-12-22 14:25 UTC, whxogus215 requested changes
단위 테스트를 통해 `UserService`의 기능을 좀 더 이해하기 쉬워진 것 같습니다 👍
간결하고, 깔끔한 테스트 코드가 좋네요.

2024-12-22 14:25 UTC, whxogus215 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
> +
각각의 `if`문을 줄바꿈으로 구분한 이유가 있으실까요? 가독성 차원에서 분리한 것이라면 줄바꿈을 하지 않더라도 가독성에는 큰 변함이 없을 것 같습니다.

2024-12-22 14:25 UTC, whxogus215 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
```java
public UserDomain create(String _studentId, String password, String email,
    MajorsDomain majorsDomain, String name) {
    Long studentId = Long.parseLong(_studentId);
    UserDomain user = UserDomain.builder()
        .studentId(studentId).password(userEncoder.encode(password))
        .email(email).majorsDomain(majorsDomain).name(name)
        .build();
    userRepository.save(user);
    return user;
}
```
해당 PR에서 변경된 부분은 아니지만 이 부분에 대한 궁금증이 있어서 코멘트를 남깁니다.
매개변수에 사용된 `_studentId`는 파싱된 `studentId`와 구분하기 위해 사용된 변수이름인걸까요?
언더바 대신에 보다 효과적인 변수 네이밍은 없을까요?

2024-12-22 14:25 UTC, whxogus215 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
> +    private UserDomain findUserByStudentId(Long studentId) {
이 부분을 `private` 함수로 분리시킨 것은 추후 재사용이 될 가능성이 있어서 분리한걸까요?

2024-12-22 14:25 UTC, whxogus215 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
> +        if (testInfo.getTags().contains("setupRequired")) {
`@Tag`를 활용해서 특정 조건에 맞는 메서드에만 별도의 작업을 지정할 수 있군요! 좋은 방법이네요 👍

2024-12-22 14:25 UTC, whxogus215 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
>          //givne, when
`//givne` 에 오타가 있습니다! 제가 코드를 작성했을 때 냈던 오타같네요.

2024-12-22 14:25 UTC, whxogus215 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
> +    void withdrawal로_유저를_삭제할_수_있다() {
메서드 명이 문장 형식으로 끝나고, 한글로 표현되어 있어서 테스트 코드를 일종의 문서로 활용할 수도 있을 것 같습니다 👍 저는 보통 메서드 이름은 영어로 하고, 테스트 실행 시 표시되는 내용은 한글로 표기하기 위해 `@DisplayName`을 활용하는데요! 제가 `@DisplayName`을 사용하는 이유는 다음과 같습니다.

1. 메서드 이름의 공백에 언더바(`_`)를 붙이지 않아도 된다.
2. 공백, 이모지 등을 자유롭게 사용할 수 있다.
3. IDE, 빌드 도구에서 수행되는 테스트 메서드에 대한 상세정보를 제공하는 용도의 어노테이션이기 때문이다.
(https://junit.org/junit5/docs/5.0.3/api/org/junit/jupiter/api/DisplayName.html)

리뷰이님은 둘 중 어느 방식을 선호하시는지 궁금합니다.

제가 초기에 작성한 테스트 코드의 메서드에는 언더바 형식으로 사용했었네요 ㅎㅎ

2024-12-22 14:25 UTC, whxogus215 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
> +    void joinValidation_가입검증_성공() {
현재 테스트 메서드의 이름이 문장 형식으로 끝나는 것과 단답 형식으로 끝나는 두 가지 버전이 섞여있는 것 같은데 통일성을 위해 한 가지로 정하는건 어떨까요?

2024-12-27 14:59 UTC, gmltn9233 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
>          //givne, when
> `//givne` 에 오타가 있습니다! 제가 코드를 작성했을 때 냈던 오타같네요.

수정완료했습니다👍

2024-12-27 14:59 UTC, gmltn9233 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
> +    void withdrawal로_유저를_삭제할_수_있다() {
> 메서드 명이 문장 형식으로 끝나고, 한글로 표현되어 있어서 테스트 코드를 일종의 문서로 활용할 수도 있을 것 같습니다 👍 저는 보통 메서드 이름은 영어로 하고, 테스트 실행 시 표시되는 내용은 한글로 표기하기 위해 `@DisplayName`을 활용하는데요! 제가 `@DisplayName`을 사용하는 이유는 다음과 같습니다.
> 
> 1. 메서드 이름의 공백에 언더바(`_`)를 붙이지 않아도 된다.
> 2. 공백, 이모지 등을 자유롭게 사용할 수 있다.
> 3. IDE, 빌드 도구에서 수행되는 테스트 메서드에 대한 상세정보를 제공하는 용도의 어노테이션이기 때문이다.
>    (https://junit.org/junit5/docs/5.0.3/api/org/junit/jupiter/api/DisplayName.html)
> 
> 리뷰이님은 둘 중 어느 방식을 선호하시는지 궁금합니다.
> 
> 제가 초기에 작성한 테스트 코드의 메서드에는 언더바 형식으로 사용했었네요 ㅎㅎ

저도 `@DisplayName` 방식을 선호하긴합니다만, 기존 테스트 코드가 언더바 형식으로 작성되어 있어 기존의 형식을 따른것 같네요. 사실 메서드명을 영어로 짓는것이 귀찮아서 해당 방식을 쓴 이유도 있지만요 ㅋㅋ
앞으로는 테스트 코드를 작성할때 `@DisplayName` 으로 통일하면 좋을것 같습니다!

2024-12-27 14:59 UTC, gmltn9233 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
> +    void joinValidation_가입검증_성공() {
> 현재 테스트 메서드의 이름이 문장 형식으로 끝나는 것과 단답 형식으로 끝나는 두 가지 버전이 섞여있는 것 같은데 통일성을 위해 한 가지로 정하는건 어떨까요?

좋은 지적 감사합니다. 앞서 말해주신 `@DisplayName` 형식으로 통일하는 과정에서 단답식으로 통일하였습니다.

2024-12-27 14:59 UTC, gmltn9233 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
> ```java
> public UserDomain create(String _studentId, String password, String email,
>     MajorsDomain majorsDomain, String name) {
>     Long studentId = Long.parseLong(_studentId);
>     UserDomain user = UserDomain.builder()
>         .studentId(studentId).password(userEncoder.encode(password))
>         .email(email).majorsDomain(majorsDomain).name(name)
>         .build();
>     userRepository.save(user);
>     return user;
> }
> ```
> 
> 해당 PR에서 변경된 부분은 아니지만 이 부분에 대한 궁금증이 있어서 코멘트를 남깁니다. 매개변수에 사용된 `_studentId`는 파싱된 `studentId`와 구분하기 위해 사용된 변수이름인걸까요? 언더바 대신에 보다 효과적인 변수 네이밍은 없을까요?

```java
public UserDomain create(String id, String password, String email,
        MajorsDomain majorsDomain, String name) {
        Long studentId = Long.parseLong(id);
        UserDomain user = UserDomain.builder()
            .studentId(studentId).password(userEncoder.encode(password))
            .email(email).majorsDomain(majorsDomain).name(name)
            .build();
        userRepository.save(user);
        return user;
    }
```
이전에 만들어진 코드라 지나쳤는데 변수명이 효과적이지 못했던것 같네요. **사용자와 로직 측면**에서 사용자는 id,pw 로직은 그것을 변환하여 `studentId`로 인식하므로 `id`와 `studentId`로 분리해보았습니다.

2024-12-27 14:59 UTC, gmltn9233 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
> +
> 각각의 `if`문을 줄바꿈으로 구분한 이유가 있으실까요? 가독성 차원에서 분리한 것이라면 줄바꿈을 하지 않더라도 가독성에는 큰 변함이 없을 것 같습니다.

줄바꿈을 했다기보다 기존에 if문 안의 `bindingResult.rejectValue` 하는 로직들을 새로운 메서드로 분리하여 `joinValidation`는 **true, false 값 반환**에만 집중하도록 했습니다.

2024-12-27 15:06 UTC, gmltn9233 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
> +    private UserDomain findUserByStudentId(Long studentId) {
> 이 부분을 `private` 함수로 분리시킨 것은 추후 재사용이 될 가능성이 있어서 분리한걸까요?
기존의 `getByStudentId` 와 `findUserByStudentId` 가 완전히 동일한 로직임을 확인하였고, 기존의 메서드를 사용하는 방식으로 리팩토링하였습니다.

2025-01-01 04:53 UTC, whxogus215 approved these changes

2025-01-01 04:53 UTC, whxogus215 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
오 의도가 확실히 와닿는 것 같습니다! 반영 감사합니다 😄

2025-01-01 04:53 UTC, whxogus215 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
> +
앗 제가 질문드린 부분은 분리시킨 각각의 if문 사이에 빈 줄이 있는데 이것이 의도한 바가 있는건지였습니다!
125번째 줄에 있는 `changePasswordValidation` 메서드와 비교하시면 제 질문을 이해하는 데에 도움이 될 것 같습니다.

2025-01-01 04:53 UTC, whxogus215 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
> +    void withdrawal로_유저를_삭제할_수_있다() {
메서드명을 영어로 짓는 것이 귀찮다는 내용도 공감합니다 😄 앞으로는 `@DisplayName`으로 통일합시다.

2025-01-01 04:53 UTC, whxogus215 commented on src/test/java/com/example/gimmegonghakauth/user/service/UserServiceTest.java
> +    void joinValidation_가입검증_성공() {
넵 테스트 코드는 `@DisplayName`을 사용하며, 단답식으로 작성하는 것으로 알고 있겠습니다. 노션에도 컨벤션으로 정리해둘게요!

2025-01-02 06:10 UTC, gmltn9233 commented on src/main/java/com/example/gimmegonghakauth/user/service/UserService.java
> +
아 리팩토링 중 붙여넣기 하는 과정에서 의미없는 줄바꿈이 들어간것 같네요! 수정했습니다.

2025-01-02 06:10 UTC, merged